---
run:
  timeout: 10m
  build-tags:
    - e2e
    - integration

issues:
  exclude:
    # golint: False positives for multi-file packages
    - 'should have a package comment'
    # gosec: Duplicate of errcheck
    - 'G104: Errors unhandled'
    - 'G307: Deferring unsafe method'
    # ineffassign/staticcheck: Contexts should be overridden defensively
    - 'ineffectual assignment to `ctx`'
    - 'SA4006: this value of `ctx` is never used'
  exclude-rules:
    - path: '_test\.go'
      linters:
        - bodyclose
        - gocognit
        - goconst
        - gocyclo
        - gosec
        - lll
        - prealloc
        - errcheck
    - text: 'SA5008:'
      linters:
        - staticcheck
  exclude-use-default: false

linters:
  enable:
    - bodyclose
    - exportloopref
    - goconst
    - gocognit
    - gocyclo
    - godot
    - gofumpt
    - goimports
    - gosec
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam

linters-settings:
  errcheck:
    exclude-functions:
      - (*database/sql.DB).Close
      - (*database/sql.Rows).Close
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write
  goconst:
    min-len: 0
    min-occurrences: 3
  gocyclo:
    min-complexity: 10
  revive:
    confidence: 0.0
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 0
