project_name: docker-credential-vault-login
builds:
  - main: ./vault-login/cli/docker-credential-vault-login/main.go
    ldflags:
      - -s -w
      - -X "github.com/morningconsult/docker-credential-vault-login/vault-login/version.Version={{ .Version }}"
      - -X "github.com/morningconsult/docker-credential-vault-login/vault-login/version.Commit={{ .ShortCommit }}"
      - -X "github.com/morningconsult/docker-credential-vault-login/vault-login/version.Date={{ time "Jan 02, 2006" }}"
    env:
    - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
archive:
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
