// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.morningconsult.com/mci/docker-credential-vault-login/vault-login/aws (interfaces: Client)

// Package mock_aws is a generated GoMock package.
package mock_aws

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	aws "gitlab.morningconsult.com/mci/docker-credential-vault-login/vault-login/aws"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetIAMAuthElements mocks base method
func (m *MockClient) GetIAMAuthElements(arg0 string) (*aws.IAMAuthElements, error) {
	ret := m.ctrl.Call(m, "GetIAMAuthElements", arg0)
	ret0, _ := ret[0].(*aws.IAMAuthElements)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIAMAuthElements indicates an expected call of GetIAMAuthElements
func (mr *MockClientMockRecorder) GetIAMAuthElements(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIAMAuthElements", reflect.TypeOf((*MockClient)(nil).GetIAMAuthElements), arg0)
}
