// Copyright 2018 The Morning Consult, LLC or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//         https://www.apache.org/licenses/LICENSE-2.0
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/morningconsult/docker-credential-vault-login/vault-login/aws (interfaces: Client)

// Package mock_aws is a generated GoMock package.
package mock_aws

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	aws "github.com/morningconsult/docker-credential-vault-login/vault-login/aws"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetIAMAuthElements mocks base method
func (m *MockClient) GetIAMAuthElements(arg0 string) (*aws.IAMAuthElements, error) {
	ret := m.ctrl.Call(m, "GetIAMAuthElements", arg0)
	ret0, _ := ret[0].(*aws.IAMAuthElements)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIAMAuthElements indicates an expected call of GetIAMAuthElements
func (mr *MockClientMockRecorder) GetIAMAuthElements(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIAMAuthElements", reflect.TypeOf((*MockClient)(nil).GetIAMAuthElements), arg0)
}

// GetPKCS7Signature mocks base method
func (m *MockClient) GetPKCS7Signature() (string, error) {
	ret := m.ctrl.Call(m, "GetPKCS7Signature")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPKCS7Signature indicates an expected call of GetPKCS7Signature
func (mr *MockClientMockRecorder) GetPKCS7Signature() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPKCS7Signature", reflect.TypeOf((*MockClient)(nil).GetPKCS7Signature))
}
