name: Test

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
    paths-ignore:
      - VERSION
      - CHANGELOG.md
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run linting and tests
    runs-on: ubuntu-18.04
    container:
      image: golang:1.17.5-alpine3.14
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run linting
      env:
        CGO_ENABLED: '0'
      run: |
        apk add -qU --no-cache --no-progress curl git
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1
        CGO_ENABLED=0 golangci-lint run

    - name: Run tests
      env:
        CGO_ENABLED: '0'
      run: go test ./...
